export const ADD_FAMILY_MEMBER = "ADD_FAMILY_MEMBER";
export const REMOVE_FAMILY_MEMBER = "REMOVE_FAMILY_MEMBER";
export const SHUFFLE_FAMILY_MEMBERS = "SHUFFLE_FAMILY_MEMBERS";
export const RESET_STATE = "RESET_STATE";
export const CHECK_DRAW = "CHECK_DRAW";
